/* Original October activities based on Ontario Mathematics 2020, Grade 2 D1. */
window.STADIUM_CURRICULUM={
 'D1.1':'Sort sets of data about people or things according to two attributes, using tables and logic diagrams, including Venn and Carroll diagrams.',
 'D1.2':'Collect data through observations, experiments, and interviews to answer questions of interest that focus on two pieces of information, and organize the data in two-way tally tables.',
 'D1.3':'Display sets of data, using one-to-one correspondence, in concrete graphs, pictographs, line plots, and bar graphs with proper sources, titles, and labels.',
 'D1.4':'Identify the mode(s), if any, for various data sets presented in concrete graphs, pictographs, line plots, bar graphs, and tables, and explain what this measure indicates about the data.',
 'D1.5':'Analyse different sets of data presented in various ways, including in logic diagrams, line plots, and bar graphs, by asking and answering questions about the data and drawing conclusions, then make convincing arguments and informed decisions.'
};
(()=>{
 const q=(id,label,answer,options)=>({id,label,answer,options});
 const nums=n=>Array.from({length:n+1},(_,i)=>i);
 const it=(id,label,emoji,target)=>({id,label,emoji,target});
 const meta=(title,label,source,unitName)=>({graphTitle:title,label,source,unitName,unit:1});
 const collect=(title,icon,method,rows,columns,records,fields,source)=>({title,icon,strand:'D1.2',type:'collect2',method,rows,columns,records,fields,source,prompt:'Reveal each record. Keep both pieces of information together, then complete all cells of the two-way tally table.',questions:[q('method','How were these data collected?',method==='interview'?'Interview':method==='experiment'?'Experiment':'Observation',['Observation','Interview','Experiment'])]});
 const plot=(title,categories,values,records,label,source)=>({title,strand:'D1.3',type:'lineplot',icon:'✕',categories,values,records,...meta(title,label,source,'records'),prompt:'Build the line plot. Add one X for each record above its number. Remove an X if you need to change it.'});
 const mode=(title,display,categories,values,modes,emoji,source,explanation)=>({title,icon:emoji,strand:'D1.4',type:'mode',display,categories,values,modes,emoji,options:[...categories,'No mode'],unit:1,max:Math.max(...values)+1,source,prompt:'Look at the data. Select all modes, or choose No mode. Then tell what the result means.',questions:[q('meaning','What do the modes tell us?',explanation,[explanation,'The mode is always the biggest category label.','The mode is the total of all the counts.'])]});
 const analysis=(title,display,categories,values,source,questions,extra={})=>({title,icon:'🔎',strand:'D1.5',type:'analyse',display,categories,values,unit:1,max:Math.max(...values)+1,source,prompt:'Read the data carefully. Answer each question using evidence from this display.',questions,...extra});
 const groups={
 A:[
 {title:'Apple sorting table',strand:'D1.1',type:'sort',layout:'table2',icon:'🍎',prompt:'Drag each apple to the table using two attributes: colour and size.',columns:['Small','Large'],rows:['Red','Green'],groups:['Red · Small','Red · Large','Green · Small','Green · Large'],items:[it('a','Red, small apple','🍎',0),it('b','Green, large apple','🍏',3),it('c','Red, large apple','🍎',1),it('d','Green, small apple','🍏',2),it('e','Green, small apple','🍏',2),it('f','Red, large apple','🍎',1)],questions:[q('rule','Which two attributes did you use?','Colour and size',['Colour and size','Colour and taste','Size and weight'])]},
 collect('Interview at the apple farm','🍎','interview',['Gala','McIntosh'],['Small bag','Large bag'],[[0,0],[1,1],[0,1],[0,0],[1,0],[0,1],[1,1],[0,0],[1,1],[0,1]],['Apple choice','Bag size'],'Simulated apple-farm interviews, October'),
 {title:'Apple-picking pictograph',strand:'D1.3',type:'pictograph',icon:'🍎',emoji:'🍎',categories:['Gala','McIntosh','Honeycrisp'],values:[5,3,4],...meta('Apples picked on Monday','Apple variety','Monday orchard count','apples'),prompt:'Build a pictograph from the table. Each whole apple picture represents ONE apple.'},
 plot('Apples in lunch bags',[1,2,3,4],[1,2,3,2],[3,2,4,3,1,4,2,3],'Apples in one bag','Eight lunch-bag observations, October'),
 mode('Most common apple choice','picture',['Gala','McIntosh','Honeycrisp'],[5,3,4],['Gala'],'🍎','Class apple survey','Gala is the most common choice, with 5 votes.'),
 analysis('Choose apples for the class','picture',['Gala','McIntosh','Honeycrisp'],[5,3,4],'Class apple survey',[q('most','Which apple has the most votes?','Gala',['Gala','McIntosh','Honeycrisp']),q('difference','How many more votes does Gala have than McIntosh?',2,nums(10)),q('total','How many votes are shown?',12,nums(15)),q('decision','Which choice is supported by the votes?','Bring more Gala apples than McIntosh apples.',['Bring more Gala apples than McIntosh apples.','Bring no Honeycrisp apples.','Everyone chose Gala.'])],{emoji:'🍎',graphTitle:'Our apple choices',label:'Apple variety',unitName:'votes'})
 ],
 B:[
 {title:'Halloween button Carroll diagram',strand:'D1.1',type:'sort',layout:'carroll',icon:'⭐',prompt:'Sort each button by colour and shape: blue or not blue; star or not a star.',columns:['Blue','Not blue'],rows:['Star','Not a star'],groups:['Blue star','Star, not blue','Blue, not a star','Not blue, not a star'],items:[it('a','Blue star','★',0),it('b','Orange heart','♥',3),it('c','Blue circle','●',2),it('d','Purple star','★',1),it('e','Green triangle','▲',3),it('f','Blue star','★',0)],questions:[q('rule','Where does a blue heart belong?','Blue, not a star',['Blue star','Star, not blue','Blue, not a star','Not blue, not a star'])]},
 collect('Costume interviews','🎃','interview',['Owl class','Fox class'],['Robot','Cat','Astronaut'],[[0,0],[1,1],[0,2],[1,0],[0,1],[1,1],[0,0],[1,2],[0,1],[1,1],[0,0],[1,0]],['Class','Costume'],'Simulated costume interviews, October'),
 {title:'Costume parade bar graph',strand:'D1.3',type:'bar',icon:'🎃',categories:['Robot','Cat','Astronaut'],values:[4,6,3],max:8,control:'select',yLabel:'Number of children',...meta('Costumes at the parade','Costume','Parade entrance tally, October','children'),prompt:'Choose each bar height. Start at zero and count by ONE child per grid interval.'},
 {title:'Concrete graph of Halloween counters',strand:'D1.3',type:'concrete',icon:'🎃',emoji:'🎃',emojis:['🎃','👻','🐈'],categories:['Pumpkin','Ghost','Cat'],values:[4,3,5],...meta('Halloween counter collection','Counter type','Classroom counter count, October','counters'),prompt:'Drag one object for each counter into its graph column. You can move objects again or return them to the bank.'},
 mode('Two popular costume choices','bar',['Robot','Cat','Astronaut'],[4,4,2],['Robot','Cat'],'🎃','Costume-choice tally','Robot and Cat are both most common, with 4 votes each.'),
 analysis('Plan the costume photo','bar',['Robot','Cat','Astronaut'],[4,6,3],'Parade entrance tally, October',[q('least','Which costume group is smallest?','Astronaut',['Robot','Cat','Astronaut']),q('difference','How many more Cats than Robots?',2,nums(8)),q('total','How many children are shown?',13,nums(16)),q('plan','Which group needs the most places in the photo?','Cat',['Robot','Cat','Astronaut'])],{graphTitle:'Costume parade',label:'Costume',yLabel:'Number of children'})
 ],
 C:[
 {title:'Toy-vehicle Venn diagram',strand:'D1.1',type:'sort',layout:'venn',icon:'🚚',prompt:'Sort by two attributes: red and truck. Use the overlap for both, and the outside box for neither.',attributes:['Red','Truck'],groups:['Red only','Red AND truck','Truck only','Neither'],items:[it('a','Red car','🚗',0),it('b','Red truck','🚚',1),it('c','Blue truck','🚚',2),it('d','Yellow car','🚗',3),it('e','Red bus','🚌',0),it('f','Green truck','🚚',2)],questions:[q('both','What does the overlap mean?','Both red and a truck',['Only red','Only a truck','Both red and a truck'])]},
 collect('Toy ramp investigation','🚗','experiment',['Car','Truck'],['2 tiles','3 tiles'],[[0,1],[1,0],[0,0],[1,0],[0,1],[1,1],[0,1],[1,0]],['Vehicle','Distance travelled'],'Simulated trials using one ramp and starting line'),
 {title:'Toy-drive bars',strand:'D1.3',type:'bar',icon:'🚚',categories:['Cars','Trucks','Buses'],values:[5,3,7],max:8,control:'slider',yLabel:'Number of toys',...meta('Toys collected in October','Vehicle type','School toy-drive count','toys'),prompt:'Slide each bar to match the table. One grid interval means ONE toy.'},
 plot('Lego tower height line plot',[2,3,4,5],[2,4,1,2],[3,2,5,3,4,3,2,5,3],'Tower height in bricks','Nine tower measurements at the fall fair'),
 mode('Most common tower height','lineplot',[2,3,4,5],[2,4,1,2],[3],'🧱','Nine tower measurements','A height of 3 bricks occurs most often: 4 towers.'),
 analysis('Read a button Carroll diagram','readCarroll',[],[2,1,1,2],'Craft-table button count',[q('blueStars','How many blue stars?',2,nums(8)),q('blueAll','How many blue buttons altogether?',3,nums(8)),q('allStars','How many stars altogether?',3,nums(8)),q('total','How many buttons are shown?',6,nums(10))],{columns:['Blue','Not blue'],rows:['Star','Not a star'],cells:[['Blue star A','Blue star B'],['Orange star C'],['Blue heart D'],['Purple heart E','Green circle F']]})
 ],
 D:[
 {title:'Game-card sorting table',strand:'D1.1',type:'sort',layout:'table2',icon:'🃏',prompt:'Sort game-character cards by two attributes: character type and card condition.',columns:['New','Worn'],rows:['Human','Creature'],groups:['Human · New','Human · Worn','Creature · New','Creature · Worn'],items:[it('a','Human · Worn','🃏',1),it('b','Creature · New','🃏',2),it('c','Human · New','🃏',0),it('d','Creature · Worn','🃏',3),it('e','Human · New','🃏',0),it('f','Creature · New','🃏',2)],questions:[q('rule','Which two attributes are used?','Character type and condition',['Character type and condition','Colour and size','Price and weight'])]},
 collect('Observe the game-card collection','🃏','observation',['Human','Creature'],['New','Worn'],[[0,0],[1,1],[0,1],[1,0],[1,0],[0,0],[1,1],[1,0],[0,1],[1,0]],['Character type','Condition'],'Ten classroom game-card observations'),
 {title:'Concrete graph of game cards',strand:'D1.3',type:'concrete',icon:'🃏',emoji:'🃏',categories:['Hero','Creature','Magic'],values:[3,5,2],...meta('Our game-card collection','Card type','Class game-card count, October','cards'),prompt:'Place one draggable object for each game card. Keep each type in its labelled graph column.'},
 {title:'Game-card pictograph',strand:'D1.3',type:'pictograph',icon:'🃏',emoji:'🃏',categories:['Hero','Creature','Magic'],values:[4,4,2],...meta('Trading cards on Friday','Card type','Friday trading-card count','cards'),prompt:'Add one whole picture for each game card. Each picture means ONE card.'},
 mode('A collection with no mode','concrete',['Hero','Creature','Magic'],[3,3,3],['No mode'],'🃏','Class game-card count','There is no mode because all three types occur equally often.'),
 analysis('Read a game-card Venn diagram','readVenn',[],[2,1,2,1],'Game-card club inventory',[q('both','How many cards are both new and shiny?',1,nums(8)),q('allNew','How many cards are new, including the overlap?',3,nums(8)),q('neither','How many cards are neither new nor shiny?',1,nums(8)),q('total','How many cards are shown altogether?',6,nums(10))],{attributes:['New','Shiny'],groups:['New only','New AND shiny','Shiny only','Neither'],cells:[['Card A','Card B'],['Card C'],['Card D','Card E'],['Card F']]})
 ],
 E:[
 {title:'Lego tower Carroll diagram',strand:'D1.1',type:'sort',layout:'carroll',icon:'🧱',prompt:'Use colour and height. Tall means 5 or more bricks. Sort each tower into the correct cell.',columns:['Red','Not red'],rows:['Tall (5 or more)','Not tall (under 5)'],groups:['Red, tall','Not red, tall','Red, not tall','Not red, not tall'],items:[it('a','Red · 6 bricks','🧱',0),it('b','Blue · 3 bricks','🧱',3),it('c','Yellow · 5 bricks','🧱',1),it('d','Red · 2 bricks','🧱',2),it('e','Red · 5 bricks','🧱',0),it('f','Green · 4 bricks','🧱',3)],questions:[q('rule','Is a tower with exactly 5 bricks tall?','Yes',['Yes','No'])]},
 collect('Paper-leaf flight experiment','🍂','experiment',['Small leaf','Large leaf'],['1 tile','2 tiles'],[[0,1],[1,0],[0,0],[1,0],[0,1],[1,1],[0,1],[1,0],[0,0],[1,0]],['Leaf size','Flight distance'],'Simulated paper-leaf trials from the same height'),
 {title:'Fall-fair visitor bars',strand:'D1.3',type:'bar',icon:'🍁',categories:['Lego table','Apple stand','Craft table'],values:[6,4,5],max:8,control:'stepper',yLabel:'Number of visitors',...meta('Visitors at our fall fair','Activity','Fall-fair entry tally','visitors'),prompt:'Press + or − to set each bar. One grid interval represents ONE visitor.'},
 plot('Books read during October',[1,2,3,4,5],[1,3,2,2,1],[2,4,3,2,5,1,4,2,3],'Books read by one child','Nine reading-log records, October'),
 {title:'Two attributes, two mode questions',strand:'D1.4',type:'analyse',display:'twoTable',icon:'🧱',rows:['Red','Blue'],columns:['2 bricks','4 bricks','6 bricks'],matrix:[[3,1,1],[1,4,2]],source:'Class tower observations',prompt:'The table records two attributes. Find the most common colour and the most common height. Add across a row or down a column.',questions:[q('colourMode','Which colour is most common?','Blue',['Red','Blue','No mode']),q('heightMode','Which height is most common?','4 bricks',['2 bricks','4 bricks','6 bricks','No mode']),q('meaning','What does the colour mode tell us?','Blue towers occur most often: 7 towers.',['Blue towers occur most often: 7 towers.','Every tower is blue.','Every blue tower is 7 bricks tall.'])]},
 analysis('Plan the October reading display','lineplot',[1,2,3,4,5],[1,3,2,2,1],'Nine reading-log records, October',[q('two','How many children read 2 books?',3,nums(10)),q('fourMore','How many children read 4 or 5 books?',3,nums(10)),q('total','How many children are shown?',9,nums(12)),q('question','Which question can this line plot answer?','How many children read 3 books?',['Which book was funniest?','How many children read 3 books?','What colour are the book covers?']),q('conclusion','Which statement is supported?','More children read 2 books than 5 books.',['More children read 2 books than 5 books.','Everyone read at least 3 books.','Nobody read 1 book.'])],{label:'Books read by one child',graphTitle:'October reading records'})
 ]};
 window.ENERGY_GROUPS=groups;
 for(const [letter,activities] of Object.entries(groups))activities.forEach((a,i)=>{a.number=i+1;a.file='Dream'+(i===0?'':i+1)+'.html';a.group=letter;if(a.type==='concrete')a.items=a.categories.flatMap((c,j)=>Array.from({length:a.values[j]},(_,k)=>it('g'+j+'-'+k,c+' '+(k+1),a.emojis?.[j]||a.emoji,j))).sort((x,y)=>x.id.split('').reverse().join('').localeCompare(y.id.split('').reverse().join('')));});
})();
